export const backendUrl = `https://mazibai.herokuapp.com/`
// export const backendUrl = `http://localhost:5000/`
export const allBooknigs = `${backendUrl}api/bookings/allbookings`
export const allUsersUrl  = `${backendUrl}api/auth/user/getall`
export const confirmBookingUrl  = `${backendUrl}api/bookings/edit/`
export  const addNotificationUrl = `${backendUrl}api/notifications/add/`
export  const bookNowUrl = `${backendUrl}api/bookings/book`
export const getallMaids = `${backendUrl}api/maid/getall`
export const addMaidUrl = `${backendUrl}api/maid/register`
export const allJobs = `${backendUrl}api/job/getall`
export const allPartners = `${backendUrl}api/partner/getall`
export const allRefers = `${backendUrl}api/maidrefer/getall`
export const loginAdmin =  `${backendUrl}api/auth/admin/login`